

services:
  mysql:
    image: mysql:8.0
    container_name: affiliate_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: affiliate_pass
      MYSQL_DATABASE: affiliate_tracking
      MYSQL_USER: affiliate_user
      MYSQL_PASSWORD: affiliate_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/migrations/schema.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: affiliate_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: affiliate_user
      DB_PASSWORD: affiliate_pass
      DB_NAME: affiliate_tracking
      PORT: 3001
      NODE_ENV: development
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: affiliate_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data:
